spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/test
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      # ddl-auto: create
      ddl-auto: update
    properties:
      hibernate:
        # show_sql: true
        format_sql: true
  jackson:
    serialization:
      INDENT_OUTPUT: true
  main:
    allow-bean-definition-overriding: true
  servlet:
    multipart:
      max-file-size: 5GB
      max-request-size: 5GB

storage:
  network-storage:
    basePath: /var/data/

logging.level:
  org.hibernate.SQL: debug
# org.hibernate.type: trace